MiniSPA/Controllers/ProductAngularController.cs
using System.Linq;
using System.Threading;
using System.Web.Mvc;
using BusinessLayer;
using MiniSPA.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;

namespace MiniSPA.Controllers
{
    [Authorize]
    public class ProductAngularController : Controller
    {
        private readonly IProductRepository _repository;

        public ProductAngularController(IProductRepository repository)
        {
            //ViewBag.AngularModule = "productModule";
            _repository = repository;
        }

        public ActionResult Index()
        {
            var products = _repository.GetAll();
            var model = products.Select(x => new ProductListViewModel()
            {
                Id = x.Id,
                Image = x.Image,
                InStock = x.InStock,
                Name = x.Name,
                Price = x.Price
            });
            return View(model);
        }

        public ActionResult Detail(int id)
        {
            var product = _repository.GetById(id);
            var model = new ProductViewModel()
            {
                Id = product.Id,
                Image = product.Image,
                InStock = product.InStock,
                Name = product.Name,
                Description = product.Description,
                Options = product.Options.Select(x => new ProductOptionViewModel()
                {
                    Image = x.Image,
                    Name = x.Name
                }).ToList(),
                Price = product.Price
            };
            return View(model);
            //var jsonSerializerSettings = new JsonSerializerSettings { ContractResolver = new CamelCasePropertyNamesContractResolver() };
            //var serialized = JsonConvert.SerializeObject(model, Formatting.None, jsonSerializerSettings);
            //return View(model: serialized);
        }
    }
}

MiniSPA/Controllers/ProductMVCController.cs
using System.Linq;
using System.Web.Mvc;
using BusinessLayer;
using MiniSPA.Models;

namespace MiniSPA.Controllers
{
    [Authorize]
    public class ProductMvcController : Controller
    {
        private readonly IProductRepository _repository;

        public ProductMvcController(IProductRepository repository)
        {
            _repository = repository;
        }

        public ActionResult Index()
        {
            var products = _repository.GetAll();
            var model = products.Select(x => new ProductListViewModel()
            {
                Id = x.Id,
                Image = x.Image,
                InStock = x.InStock,
                Name = x.Name,
                Price = x.Price
            });
            return View(model);
        }

        [Authorize(Roles="Admin")]
        public ActionResult Detail(int id)
        {
            var product = _repository.GetById(id);
            var model = new ProductViewModel()
            {
                Id = product.Id,
                Image = product.Image,
                InStock = product.InStock,
                Name = product.Name,
                Description = product.Description,
                Options = product.Options.Select(x => new ProductOptionViewModel()
                {
                    Id = x.Id,
                    Image = x.Image,
                    Name = x.Name
                }).ToList(),
                Price = product.Price
            };
            return View(model);
        }
    }
}

MiniSPA/Controllers/ProductRestController.cs
using System.Web.Mvc;

namespace MiniSPA.Controllers
{
    [Authorize]
    public class ProductRestController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Detail(int id)
        {
            return View(id);
        }
    }
}

MiniSPA/Controllers/ProductRoutingController.cs
using System.Web.Mvc;

namespace MiniSPA.Controllers
{
    [Authorize]
    public class ProductRoutingController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }
    }
}

MiniSPA/Views/Shared/_Layout.cshtml
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AngularJS / ASP.NET Demo</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("AngularJS .NET", "Index", "ProductMvc", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Products-MVC", "Index", "ProductMvc")</li>
                    <li>@Html.ActionLink("Products-Angular", "Index", "ProductAngular")</li>
                    <li>@Html.ActionLink("Products-Rest", "Index", "ProductRest")</li>
                    <li>@Html.ActionLink("Products-Routing", "Index", "ProductRouting")</li>
                    @if (User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Site Admin", "Index", "Admin")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - AngularJS / ASP.NET Demo.<span class="pull-right">St. Louis Days of .NET 2014</span></p>
        </footer>
    </div>
</body>
</html>